### ISSUE TITLE
ディスプレイ買う

### ISSUE THREAD

**Issue by daicche** [re-born/tasks#1]

**Comment by pumpkinheader** [comment]
##個人で買うか・みんなで同じの買うか
##予算の管理誰がやるの？

今週買っちゃいたい

**Comment by sosuke-k** [comment]
ディスプレイに関しては俺はB4わくの誰かのをひきつぐのかな？
なので、個人かみんな同じかどっちでもいいです。

**Comment by daicche** [comment]
今日か昨日にはてブのホッテントリに入ってたやつ
Macと相性抜群な「PHILIPS 21.5型/23型 IPS液晶ワイドディスプレイ」で作業効率化！ 写真15枚レビュー＆5つのお薦めポイント
http://www.mocchiblog.com/?p=15106

**Comment by rooa** [comment]
一括楽だからこれにしましょうか
http://www.amazon.co.jp/Lulu-LAB-VGA%E7%AB%AF%E5%AD%90%E5%A4%89%E6%8F%9B%E3%82%A2%E3%83%80%E3%83%97%E3%82%BF-Displayport%E3%81%AE%E5%87%BA%E5%8A%9B%E3%82%92VGA%E7%AB%AF%E5%AD%90%E3%81%AB%E5%A4%89%E6%8F%9B-%EF%BC%8B%E3%82%AA%E3%83%BC%E3%83%87%E3%82%A3%E3%82%AA%E5%87%BA%E5%8A%9B/dp/B00G1XORKE/ref=sr_1_3?s=computers&ie=UTF8&qid=1399901670&sr=1-3&keywords=mini+displayport+vga

なぜなら、、amazonに,dell displayにはvgaケーブルついてくると書いてあるので、vga - minidisplayportのアダプタだけ買えば、ケーブル買わずに済むかと思ったからです (edited)

(レビュー微妙なので他製品考慮も)
