### ISSUE TITLE
飯島氏welcome back party案

### ISSUE THREAD

**Issue by rooa** [re-born/tasks#5]
## オーブンレンジで作るもの
- pizza
- quiche
- gouter
- 手巻き寿司
- パウンドケーキ
- スコーン

案だしてください
( ﾟ∀ﾟ)ｱﾊﾊ八八ﾉヽﾉヽﾉヽﾉ ＼ / ＼/ ＼

**Comment by pumpkinheader** [comment]
(ﾟ∀ﾟｱﾋｬ∀ﾟﾋｬ∀ﾟﾋｬ∀ﾟﾋｬ∀ﾟﾋｬ∀ﾟﾋｬ∀ﾟｬﾋ∀ﾟｬﾋ∀ﾟｬﾋ∀ﾟｬﾋ∀ﾟｬﾋ∀ﾟｬﾋｱ∀ﾟ)

**Comment by pumpkinheader** [comment]
・グラタン

**Comment by kadotami** [comment]
みんなで好きなもの挟む系サンドウィッチ

**Comment by taisho6339** [comment]
シュークリーム
